### ISSUE TITLE
Ekman emotions

### ISSUE THREAD

**Issue by jralfonsog** [JULIELab/EmoBank#1]
Hello there.

In the main README it's said that "a subset of the corpus have been previously annotated according to Ekmans 6 Basic Emotions (Strapparava and Mihalcea, 2007) so that mappings between both representation formats become possible".  Is that subset published? If not, could it be possible to get access to it?

Thanks for your time.

**Comment by svenbuechel** [comment]
Hi @jralfonsog ,
thanks for your interest!  The dataset is in fact available [here](http://web.eecs.umich.edu/~mihalcea/affectivetext/).
Best
Sven

**Comment by jralfonsog** [comment]
Thanks a lot!
